<main>
        <div class="error"><?php Session::displayErrors(); ?></div>
        <div class="success"><?php Session::displaySuccesses(); ?></div>
    <form action="<?php if ($id) : echo $id;
                    else : echo "new";
                    endif ?>" method="post" class="pure-form">
        <fieldset class="pure-group">
            <input id="name" name="name" type="text" class="pure-input-1-4" value="<?php if ($id) : echo $dish['name'];
                                                                                    endif ?>" placeholder="Nom du plat">
        </fieldset>

        <fieldset class="pure-group">
            <textarea id="description" name="description" class="pure-input-1-4" placeholder="Description"><?php if ($id) : echo $dish['description'];
                                                                                                            endif ?></textarea>
        </fieldset>

        <fieldset class="pure-group">
            <select id="type" name="type" class="pure-input-1-4" value="">
                <option value="appetizer" <?php if ($id && $dish['type'] == "appetizer") : ?>selected<?php
                                                                                                    endif ?>>Entrée</option>
                <option value="dish" <?php if ($id && $dish['type'] == "dish") : ?>selected<?php
                                                                                            endif ?>>Plat</option>
                <option value="dessert" <?php if ($id && $dish['type'] == "dessert") : ?>selected<?php
                                                                                                endif ?>>Déssert</option>
            </select>
        </fieldset>

        <fieldset class="pure-group">
            <input id="price" name="price" type="number" step="0.01" class="pure-input-1-4" value="<?php if ($id) : echo $dish['price'];
                                                                                                    endif ?>" placeholder="Prix">
        </fieldset>

        <button type="submit" class="pure-button pure-input-1-4 pure-button-primary"><?php if ($id) : echo "Modifier";
                                                                                    else : echo "Ajouter";
                                                                                    endif ?></button>
    </form>
</main>