<main>
        <div class="error"><?php Session::displayErrors(); ?></div>
        <div class="success"><?php Session::displaySuccesses(); ?></div>
    <form action="<?php if (!empty($_GET['id'])) : echo $_GET['id'];
                    else : echo "reservation";
                    endif ?>" method="post" class="pure-form pure-form-aligned">
        <fieldset>
            <div class="pure-control-group">
                <label for="name" <?php if ($_SESSION['connected']) : ?>hidden<?php endif ?>>Votre nom</label>
                <input id="name" <?php if ($_SESSION['connected']) : ?>hidden<?php endif ?> name="name" type="text" value="<?php if (!empty($_GET['id'])) : echo $reservation['name'];
                                                                else : if ($_SESSION['connected']) : echo $_SESSION['user']['lastname'];
                                                                endif;
                                                                endif ?>">
            </div>

            <div class="pure-control-group">
                <label for="email" <?php if ($_SESSION['connected']) : ?>hidden<?php endif ?>>Votre e-mail</label>
                <input id="email" <?php if ($_SESSION['connected']) : ?>hidden<?php endif ?> name="email" type="email" value="<?php if (!empty($_GET['id'])) : echo $reservation['email'];
                                                                else : if ($_SESSION['connected']) : echo $_SESSION['user']['email'];
                                                                endif;
                                                                endif ?>">
            </div>

            <div class="pure-control-group">
                <label for="date">Votre réservation</label>
                <input type="date" name="date" id="date" value="<?php if (!empty($_GET['id'])) : echo $reservation['date'];
                                                                endif ?>">
                <input type="time" name="time" id="time" min="11:45" max="21:30" value="<?php if (!empty($_GET['id'])) : echo $reservation['time']; else: echo "12:00";
                                                                endif ?>">
            </div>

            <div class="pure-control-group">
                <label for="number">Nombre de personnes</label>
                <input name="number" type="number" max="6" min="1" oninput="this.value = Math.abs(this.value)" value="<?php if (!empty($_GET['id'])) : echo $reservation['number']; else: echo "2";
                                                            endif ?>">
            </div>

            <div class="pure-controls">
                <button type="submit" class="pure-button pure-button-primary"><?php if (!empty($_GET['id'])) : echo "Modifier";
                                                                                else : echo "Valider ma réservation";
                                                                                endif ?></button>
            </div>
        </fieldset>
    </form>
    <script>
        let today = new Date().toISOString().split('T')[0];
        document.querySelector("input[type='date']").setAttribute('min', today);
    </script>
</main>