
<main>

        <div class="error"><?php Session::displayErrors(); ?></div>
        <div class="success"><?php Session::displaySuccesses(); ?></div>
    <table class="pure-table pure-table-horizontal">
        <thead>
            <tr>
                <th>Date</th>
                <th>Nom</th>
                <th>Nombre de personnes</th>
                <th>Gestion</th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($reservations as $index => $reservation) : ?>
            <tr>
                <td><?= "Le " . substr($reservation['date'], 5, -9) . " à " . substr($reservation['date'], -9, -3) ?></td>
                <td><?= $reservation['name'] ?></td>
                <td><?= $reservation['number'] ?></td>
                <td>
                    <a href="reservations/update/<?= $reservation['id'] ?>">Modifier</a>
                    <a href="reservations/delete/<?= $reservation['id'] ?>">Supprimer</a>
                </td>
            </tr>
        <?php endforeach ?>
        </tbody>
        <tfoot>
            <tr>
                <td style="text-align: right; margin-right: 15px;" colspan="4">Total : <?= count($reservations) ?></td>
            </tr>
        </tfoot>
    </table>
</main>