<main>
        <div class="error"><?php Session::displayErrors(); ?></div>
        <div class="success"><?php Session::displaySuccesses(); ?></div>
    <form action="signup" method="post" class="pure-form">
        <fieldset class="pure-group">
            <input name="firstname" type="text" class="pure-input-1-2" placeholder="Prénom">
            <input name="lastname" type="text" class="pure-input-1-2" placeholder="Nom">
        </fieldset>

         <fieldset class="pure-group">
            <input id="email" name="email" type="email" class="pure-input-1-2" placeholder="Email">
            <input type="tel" name="phone" id="" class="pure-input-1-2" placeholder="Téléphone">
        </fieldset>

        <fieldset class="pure-group">
            <input name="password" type="password" class="pure-input-1-2" placeholder="Mot de passe">
            <input name="passwordConfirm" type="password" class="pure-input-1-2" placeholder="Confirmez votre mot de passe">
        </fieldset>

        <fieldset id="subscr" class="pure-group"> 
            
            <label for="cb" class="pure-checkbox">
                <input id="cb" type="checkbox"> J'ai bien lu les petites lignes
            </label>
            <button type="submit" class="pure-button pure-input-1-2 pure-button-primary">Inscription</button>
        </fieldset>
    </form>
</main>